version: '3.3'
services:
  mysql-crud-app:
    image: mysql:8.0.27
    ports:
      - "3304:3306"
    environment:
      MYSQL_DATABASE: "crud_db"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
